include:
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_left_studio
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_right_studio
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: ergonaut_one_left_with_dongle
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_left_with_dongle_studio
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_dongle
    artifact-name: ergonaut_one_dongle
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_dongle_studio
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_dongle dongle_display
    artifact-name: ergonaut_one_dongle_display
  - board: seeeduino_xiao_ble
    shield: ergonaut_one_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: ergonaut_one_dongle_display_studio
  - board: seeeduino_xiao_ble
    shield: settings_reset
